### ISSUE TITLE
dictionary no working =(

### ISSUE THREAD

**Issue by lacoste-sochi** [ngirot/BruteForce#12]
Hello! Thanks for the work.

Dictionary search does not work =(

**Comment by ngirot** [comment]
Hello,
I tried to test the example from the README and it works for me.
Do you have an example of a command-line with a dictionary file not working for you ?

**Comment by lacoste-sochi** [comment]
I probably misunderstood how the dictionary works. Excuse me, is it possible to search by mask? For example, I know that the hash contains 5 digits in a row, but I do not know if it is at the beginning or at the end, or in the middle.

**Comment by ngirot** [comment]
No there is no such feature currently, but this is an interesting idea.
It will be complicated to implement, so I'm not sure i will do it one day... sorry.
