### ISSUE TITLE
Seems the v1.3 mac os version is not correctly build for Mac

### ISSUE THREAD

**Issue by mJace** [ngirot/BruteForce#8]
After I download v1.3 mac version. And it failed with following error
```
zsh: exec format error: ./BruteForce-macos-amd64
```

BTW v1.2 mac os version works on my mac

**Comment by ngirot** [comment]
Thank you for your feedback.
I don't have macos available for testing and trusted the go cross-compiler but it was a mistake obviously.
I will try to find a way to test it in a real context and see what's wrong.

**Comment by ngirot** [comment]
Ok, I don't know how I messed up this, but the 1.3 release of the macos version is the linux one...
I did test the next release (1.4) on a mac os and it works, i should be available in a few days.
