### ISSUE TITLE
specify the character count output

### ISSUE THREAD

**Issue by arthures11** [ngirot/BruteForce#9]
would be to cool to specify that for example the output has 10 chars and the brute would start looking by skipping 1-9 lenghts

**Comment by ngirot** [comment]
Sure, I will add a parameter in the next release. I will have some time to work on that soon.

**Comment by ngirot** [comment]
I did add the "--size" parameter to control word size with two pattern:
- Single number like "5" for a specific size
- Two numbers like "3-8" to select a range

**Comment by arthures11** [comment]
thanks!
